apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec33nw-map-gui
  labels:
    app: ec33nw-map-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ec33nw-map-gui
  template:
    metadata:
      labels:
        app: ec33nw-map-gui
    spec:
      containers:
      - name: ec33nw-map-gui
        image: zedas/ec33nw-map-gui
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: ec33nw-map-gui-service
spec:
  selector:
    app: ec33nw-map-gui
  ports:
    - port: 80
      name: defaultnginxport
      protocol: TCP
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ec33nw-map-gui-ingress
spec:
  rules:
  - host: ec33nw.map.analytics.com
    http:
      paths:
      - path: /
        pathType: Exact  
        backend:
          service:
            name: ec33nw-map-gui-service
            port: 
              number: 80



